name: Docker Image & Container CI/CD

on:
  push:
    branches: [ "master" ]
  schedule:
    -
      cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
          name: Check out repository code
          uses: actions/checkout@v3
      -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            push: true
            tags: injectrl/biliclonline:latest
      -
          name: Release server key
          run: |
            cat << EOF >> ./key.pem
            ${{ secrets.SERVER_KEY }}
      -
          name: Login server & Deploy
          uses: appleboy/ssh-action@v1.0.3
          with:
            username: ${{ secrets.SERVER_USER }}
            host: ${{ secrets.SERVER_ROUTE }}
            key_path: ./key.pem
            script: |
              sudo docker stop bcl
              sudo docker rm bcl
              sudo docker pull injectrl/biliclonline:latest
              sudo docker run -d -it --name bcl -p 5000:5000 -e HCaptchaSecret="${{ secrets.HCAPTCHASECRET }}" -e CorsTarget="${{ secrets.CORSTARGET }}" injectrl/biliclonline:latest